version: 2

models:
  - name: fct_orders
    description: Fact table for orders with customer information
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: customer_name
      - name: order_date
      - name: amount
        tests:
          - not_null

  - name: dim_customers
    description: Dimension table for customers with aggregated metrics
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: customer_name
      - name: email
      - name: total_orders
      - name: total_amount
      - name: first_order_date
      - name: last_order_date

  - name: fct_sales_minio
    description: Fact table for MinIO sales aggregated by category and region
    columns:
      - name: category
        tests:
          - not_null
      - name: region
        tests:
          - not_null
      - name: total_sales_count
      - name: total_quantity_sold
      - name: total_revenue
